<?php
/**
 * Preguntas frecuentes por página. Generan el schema FAQPage de esa página.
 * page_slug '' corresponde al inicio.
 */
return [
    // ------------------------------------------------------------------ Inicio
    ['page_slug' => '', 'question' => '¿Cuánto cuesta una página web en Guatemala?', 'answer' => '<p>Con nosotros, una página web profesional cuesta Q1,250 al año e incluye dominio, alojamiento con SSL, diseño a la medida, redacción de textos, cuentas de correo y soporte. Se arranca con Q250 y el saldo de Q1,000 se paga al aprobar el diseño. El detalle completo está en la página de <a href="/precios/">precios</a>.</p>'],
    ['page_slug' => '', 'question' => '¿En cuánto tiempo entregan un sitio?', 'answer' => '<p>Un sitio corporativo estándar toma entre dos y tres semanas desde que tenemos el pago inicial y el material completo (logo, fotos y listado de servicios). Lo que más atrasa los proyectos no es el diseño, sino esperar la información del cliente.</p>'],
    ['page_slug' => '', 'question' => '¿El dominio queda a nombre de mi empresa?', 'answer' => '<p>Sí. El dominio se registra a nombre de tu empresa o tuyo, y vos sos el titular. Nosotros solo lo administramos técnicamente. Si algún día querés llevarlo a otro proveedor, te damos los códigos de traslado.</p>'],
    ['page_slug' => '', 'question' => '¿Puedo editar el contenido yo mismo?', 'answer' => '<p>Sí. Entregamos un panel de administración en español donde podés cambiar textos, precios, fotos, publicaciones del blog y datos de contacto. Damos una capacitación por videollamada para que lo uses sin miedo.</p>'],
    ['page_slug' => '', 'question' => '¿Trabajan con clientes fuera de la capital o del país?', 'answer' => '<p>Sí. Todo el proceso es en línea: WhatsApp, correo y videollamada. Tenemos clientes en varios departamentos y también guatemaltecos que operan desde el extranjero.</p>'],
    ['page_slug' => '', 'question' => '¿Garantizan el primer lugar en Google?', 'answer' => '<p>No, y desconfiá de quien lo prometa. Lo que sí hacemos es dejar bien la parte técnica y de contenido: velocidad, estructura, títulos, datos estructurados y mapa del sitio. El posicionamiento depende además de tu competencia y del tiempo, y eso no lo controla ninguna agencia.</p>'],

    // ------------------------------------------------------------------ Precios
    ['page_slug' => 'precios', 'question' => '¿El precio de Q1,250 es por año o por una sola vez?', 'answer' => '<p>Es anual. Cubre doce meses de servicio e incluye dominio, alojamiento, certificado SSL, correos y soporte. Al año siguiente se renueva para mantener todo activo.</p>'],
    ['page_slug' => 'precios', 'question' => '¿Cómo se hacen los pagos?', 'answer' => '<p>Con un pago inicial que activa el proyecto (Q250 en página web, Q350 en tienda virtual) y el saldo al aprobar el diseño, antes de publicar. Aceptamos depósito y transferencia bancaria en quetzales.</p>'],
    ['page_slug' => 'precios', 'question' => '¿Qué pasa si no renuevo al año siguiente?', 'answer' => '<p>El sitio y los correos quedan suspendidos al vencer el período. Conservamos los archivos un tiempo prudencial por si querés reactivar. El dominio sigue siendo tuyo y te entregamos los accesos para trasladarlo.</p>'],
    ['page_slug' => 'precios', 'question' => '¿Cobran extra por cambios en el sitio?', 'answer' => '<p>Los cambios menores están incluidos y además podés hacerlos vos desde el panel. Se cotizan aparte los rediseños completos, las secciones nuevas y las funciones adicionales, como un sistema de citas o una integración con otro sistema.</p>'],
    ['page_slug' => 'precios', 'question' => '¿Los precios incluyen IVA?', 'answer' => '<p>Los precios publicados son los que se facturan. Al momento de cotizar te confirmamos por escrito el monto exacto y la forma de facturación, para que no haya sorpresas.</p>'],
    ['page_slug' => 'precios', 'question' => '¿Por qué la tienda aparece con precio tachado de Q3,600?', 'answer' => '<p>Q3,600 es el precio normal de la tienda virtual. Q1,750 es el precio de lanzamiento con el que estamos trabajando actualmente. Cuando ese precio cambie, lo actualizamos en esta misma página.</p>'],

    // ------------------------------------------------------- Diseño de páginas
    ['page_slug' => 'diseno-de-paginas-web-guatemala', 'question' => '¿Usan plantillas o diseñan desde cero?', 'answer' => '<p>Partimos de nuestro propio sistema de diseño y lo adaptamos a cada negocio: colores, tipografía, estructura de secciones y fotografías. No compramos plantillas de catálogo que ya estén usando otros negocios en Guatemala.</p>'],
    ['page_slug' => 'diseno-de-paginas-web-guatemala', 'question' => '¿Cuántas páginas incluye el sitio?', 'answer' => '<p>Las que tenga sentido incluir según tu negocio. Un sitio corporativo típico lleva inicio, servicios, nosotros, portafolio, preguntas frecuentes y contacto. Si un servicio tuyo merece su propia página porque la gente lo busca por separado, la hacemos.</p>'],
    ['page_slug' => 'diseno-de-paginas-web-guatemala', 'question' => '¿Quién escribe los textos?', 'answer' => '<p>Nosotros. Vos nos contás a qué te dedicás y qué te preguntan tus clientes, y con eso redactamos. Después revisás y corregís lo que solo vos sabés: nombres técnicos, garantías, cobertura y condiciones.</p>'],
    ['page_slug' => 'diseno-de-paginas-web-guatemala', 'question' => '¿Qué pasa si no tengo fotos de mi negocio?', 'answer' => '<p>Te decimos exactamente qué fotos tomar y cómo, para que con un celular reciente y luz de día tengas material aprovechable. Para lo que no se puede fotografiar usamos ilustraciones propias. No usamos fotos de bancos de imágenes que ya estén en otros veinte sitios.</p>'],
    ['page_slug' => 'diseno-de-paginas-web-guatemala', 'question' => '¿Puedo mover mi sitio actual con ustedes?', 'answer' => '<p>Sí, siempre que tengás los accesos. Revisamos qué se puede aprovechar del contenido, migramos el sitio o lo rehacemos según convenga, y configuramos las redirecciones para no perder el posicionamiento que ya tenías.</p>'],
    ['page_slug' => 'diseno-de-paginas-web-guatemala', 'question' => '¿El sitio funciona bien en celular?', 'answer' => '<p>Sí, y es lo primero que diseñamos. Probamos el sitio en anchos de 360, 390, 768, 1024 y 1440 píxeles antes de publicar, porque la mayoría de tus visitas van a llegar desde un teléfono.</p>'],

    // -------------------------------------------------------- Tiendas virtuales
    ['page_slug' => 'tiendas-virtuales-guatemala', 'question' => '¿Qué plataforma usan para las tiendas?', 'answer' => '<p>WooCommerce sobre WordPress, instalado en tu propio alojamiento. Es la plataforma de comercio más usada del mundo, no cobra comisión por venta y te deja llevarte la tienda a donde quieras.</p>'],
    ['page_slug' => 'tiendas-virtuales-guatemala', 'question' => '¿Cuánto cuesta poder cobrar con tarjeta?', 'answer' => '<p>La integración con Visanet Epay cuesta Q750 al año adicionales al plan de tienda. Aparte, tu empresa debe afiliarse con el banco, que define la comisión por transacción. Esa afiliación se contrata directamente con la entidad bancaria.</p>'],
    ['page_slug' => 'tiendas-virtuales-guatemala', 'question' => '¿Cuántos productos puedo subir?', 'answer' => '<p>No ponemos un límite artificial. Nosotros cargamos un primer grupo de productos para dejar la tienda funcionando y capacitarte, y de ahí en adelante vos podés seguir agregando los que necesités desde el panel.</p>'],
    ['page_slug' => 'tiendas-virtuales-guatemala', 'question' => '¿Cómo se manejan los envíos?', 'answer' => '<p>Configuramos tarifas distintas para la capital y el interior, retiro en tienda y, si querés, envío gratis a partir de cierto monto. El cliente ve el costo del envío antes de confirmar el pedido.</p>'],
    ['page_slug' => 'tiendas-virtuales-guatemala', 'question' => '¿La tienda emite factura electrónica?', 'answer' => '<p>WooCommerce genera el comprobante del pedido, que no es lo mismo que una factura FEL. Para emitir factura electrónica se necesita un proveedor certificado por la SAT. Podemos revisar con vos las opciones y cómo encajarlas en el flujo de pedidos.</p>'],
    ['page_slug' => 'tiendas-virtuales-guatemala', 'question' => '¿Me sirve una tienda si vendo servicios?', 'answer' => '<p>Depende. Si tu servicio tiene precio fijo y se puede pagar por adelantado, sí. Si cada trabajo se cotiza aparte, normalmente te sirve más una página web con catálogo y formulario de cotización. Te lo decimos antes de venderte la tienda.</p>'],

    // ------------------------------------------------------------------- Correo
    ['page_slug' => 'cuentas-de-correo-corporativo', 'question' => '¿Necesito una página web para tener correo con mi dominio?', 'answer' => '<p>No necesariamente. Se puede configurar el correo con tu dominio aunque todavía no tengás sitio. Ahora bien, si ya vas a pagar dominio y alojamiento, el paso a tener también la página es corto.</p>'],
    ['page_slug' => 'cuentas-de-correo-corporativo', 'question' => '¿Por qué mis correos caen en spam?', 'answer' => '<p>Casi siempre es porque faltan los registros SPF y DKIM del dominio, o porque se está enviando desde una dirección IP con mala reputación. Revisamos ambas cosas y dejamos la configuración correcta.</p>'],
    ['page_slug' => 'cuentas-de-correo-corporativo', 'question' => '¿Puedo seguir usando Gmail para leer mi correo de empresa?', 'answer' => '<p>Sí. Se puede configurar tu cuenta corporativa dentro de la aplicación de Gmail o de cualquier otro cliente de correo, para que escribas desde tu dominio pero sigas usando la interfaz que ya conocés.</p>'],
    ['page_slug' => 'cuentas-de-correo-corporativo', 'question' => '¿Migran los correos que ya tengo?', 'answer' => '<p>Cuando la plataforma de origen lo permite, sí: trasladamos las cuentas y el historial. Coordinamos el cambio para que la interrupción sea mínima y te avisamos qué hacer durante la transición.</p>'],

    // ------------------------------------------------- Página de preguntas frecuentes
    ['page_slug' => 'preguntas-frecuentes', 'question' => '¿Qué diferencia hay entre paginasweb.gt y Servicom?', 'answer' => '<p>Ninguna en cuanto a equipo, precios y contacto: paginasweb.gt es la marca comercial con la que Servicom presenta su servicio de sitios y tiendas. Mismo teléfono, mismo correo, mismas personas. Podés leer más en <a href="/nosotros/">Nosotros</a>.</p>'],
    ['page_slug' => 'preguntas-frecuentes', 'question' => '¿Hacen aplicaciones móviles o sistemas a la medida?', 'answer' => '<p>No. Nos dedicamos a sitios web, tiendas en línea y correo corporativo. Si tu proyecto es una aplicación o un sistema interno, te lo decimos de una vez en lugar de aceptar algo que no es lo nuestro.</p>'],
    ['page_slug' => 'preguntas-frecuentes', 'question' => '¿Manejan publicidad en Google o Facebook?', 'answer' => '<p>No gestionamos campañas pagadas. Dejamos el sitio y la analítica listos para que quien maneje tu publicidad pueda medir resultados sin problemas.</p>'],
    ['page_slug' => 'preguntas-frecuentes', 'question' => '¿Firman contrato?', 'answer' => '<p>La relación se rige por los <a href="/terminos-y-condiciones/">términos y condiciones</a> publicados, que se aceptan con el primer pago. Si tu empresa necesita un documento firmado para su proceso interno, lo preparamos sin problema.</p>'],
    ['page_slug' => 'preguntas-frecuentes', 'question' => '¿Qué pasa si mi sitio se cae o lo hackean?', 'answer' => '<p>Contás con soporte durante el período contratado. Restauramos desde los respaldos del alojamiento y revisamos qué lo causó. Si el problema vino de una intervención de terceros ajenos a nuestro equipo, la recuperación se cotiza aparte.</p>'],
    ['page_slug' => 'preguntas-frecuentes', 'question' => '¿Me entregan los accesos si me quiero cambiar de proveedor?', 'answer' => '<p>Sí. Estando al día en pagos, te entregamos los archivos del sitio y los accesos del dominio. Nunca hemos considerado que retener un dominio sea una forma decente de conservar un cliente.</p>'],
];
