<?php
/**
 * Servicios y planes de precios.
 * Precios vigentes de Servicom / paginasweb.gt en quetzales.
 */
return [
    [
        'slug'       => 'paginas-web',
        'name'       => 'Diseño de páginas web',
        'short_name' => 'Página web',
        'tagline'    => 'Un sitio propio, rápido y administrable, listo para recibir clientes desde el celular.',
        'summary'    => 'Diseñamos el sitio completo: estructura, textos guiados, formulario, botón de WhatsApp y todo lo necesario para que tu negocio se vea serio en internet. Incluye dominio, alojamiento y soporte durante el año.',
        'icon'       => 'browser',
        'page_slug'  => 'diseno-de-paginas-web-guatemala',
        'sort_order' => 1,
        'plans' => [
            [
                'name'            => 'Página web profesional',
                'badge'           => 'El más pedido',
                'price'           => 1250.00,
                'price_strike'    => null,
                'period'          => 'al año',
                'price_note'      => 'Empezás con Q250 y el saldo de Q1,000 se paga al aprobar el diseño.',
                'initial_payment' => 250.00,
                'balance_payment' => 1000.00,
                'features' => [
                    'Dominio .com o .gt incluido el primer año',
                    'Alojamiento web con certificado SSL',
                    'Diseño a la medida de tu negocio (sin plantillas recicladas)',
                    'Secciones que necesitás: inicio, servicios, nosotros, galería y contacto',
                    'Adaptado a celular, tablet y computadora',
                    'Formulario de contacto que llega a tu correo',
                    'Botón de WhatsApp en todas las páginas',
                    'Cuentas de correo con tu dominio',
                    'Carga de tus textos y fotos por nuestro equipo',
                    'Soporte y cambios menores durante el año',
                ],
                'cta_text'  => 'Cotizar mi página web',
                'cta_url'   => '/contacto/',
                'featured'  => 1,
                'sort_order'=> 1,
            ],
        ],
    ],
    [
        'slug'       => 'tiendas-virtuales',
        'name'       => 'Tiendas virtuales',
        'short_name' => 'Tienda virtual',
        'tagline'    => 'Vendé en línea con catálogo, carrito y cobro con tarjeta desde tu propio dominio.',
        'summary'    => 'Montamos tu tienda sobre WooCommerce, con tu catálogo cargado, opciones de envío para Guatemala y la posibilidad de cobrar con tarjeta a través de Visanet Epay. Vos administrás productos y pedidos.',
        'icon'       => 'cart',
        'page_slug'  => 'tiendas-virtuales-guatemala',
        'sort_order' => 2,
        'plans' => [
            [
                'name'            => 'Tienda virtual WooCommerce',
                'badge'           => 'Precio de lanzamiento',
                'price'           => 1750.00,
                'price_strike'    => 3600.00,
                'period'          => 'al año',
                'price_note'      => 'Empezás con Q350 y el saldo de Q1,400 se paga al aprobar la tienda.',
                'initial_payment' => 350.00,
                'balance_payment' => 1400.00,
                'features' => [
                    'Tienda en línea sobre WooCommerce (WordPress)',
                    'Dominio y alojamiento con SSL incluidos el primer año',
                    'Catálogo con categorías, fotos, precios y existencias',
                    'Carrito y proceso de compra en español',
                    'Opciones de envío por departamento y retiro en tienda',
                    'Pago contra entrega y depósito o transferencia bancaria',
                    'Panel para que administrés productos y pedidos',
                    'Capacitación por videollamada para tu equipo',
                    'Adaptada a celular, que es donde compra la mayoría',
                    'Soporte durante el año',
                ],
                'cta_text'  => 'Quiero mi tienda en línea',
                'cta_url'   => '/contacto/',
                'featured'  => 1,
                'sort_order'=> 1,
            ],
            [
                'name'            => 'Cobro con tarjeta (Visanet Epay)',
                'badge'           => 'Complemento',
                'price'           => 750.00,
                'price_strike'    => null,
                'period'          => 'al año adicional',
                'price_note'      => 'Se suma al plan de tienda virtual. La afiliación con Visanet y sus comisiones se contratan directamente con el banco.',
                'initial_payment' => null,
                'balance_payment' => null,
                'features' => [
                    'Integración de la pasarela Visanet Epay a tu tienda',
                    'Cobro con tarjeta Visa y Mastercard en quetzales',
                    'Pruebas de compra antes de salir a producción',
                    'Acompañamiento en el trámite de afiliación con el banco',
                    'Mantenimiento de la integración durante el año',
                ],
                'cta_text'  => 'Consultar cobro con tarjeta',
                'cta_url'   => '/contacto/',
                'featured'  => 0,
                'sort_order'=> 2,
            ],
        ],
    ],
    [
        'slug'       => 'correo-corporativo',
        'name'       => 'Cuentas de correo corporativo',
        'short_name' => 'Correo corporativo',
        'tagline'    => 'Escribí desde tu dominio y dejá de mandar cotizaciones con una dirección de Gmail.',
        'summary'    => 'Configuramos cuentas con tu propio dominio, las dejamos funcionando en tu celular y en tu computadora, y ordenamos los registros de correo para que tus mensajes no caigan en spam.',
        'icon'       => 'mail',
        'page_slug'  => 'cuentas-de-correo-corporativo',
        'sort_order' => 3,
        'plans' => [
            [
                'name'            => 'Correo con tu dominio',
                'badge'           => null,
                'price'           => null,
                'price_text'      => 'Consultar',
                'price_strike'    => null,
                'period'          => 'según cantidad de cuentas',
                'price_note'      => 'El precio depende de cuántas cuentas necesitás y del espacio de cada una. Si ya tenés página con nosotros, las cuentas van incluidas en tu plan.',
                'initial_payment' => null,
                'balance_payment' => null,
                'features' => [
                    'Cuentas nombre@tudominio.com',
                    'Configuración en celular Android y iPhone',
                    'Configuración en Outlook y en el correo del Mac',
                    'Acceso por navegador (webmail) desde cualquier lugar',
                    'Registros SPF y DKIM para reducir el spam',
                    'Traslado de correos si venís de otro proveedor',
                ],
                'cta_text'  => 'Consultar precio de correo',
                'cta_url'   => '/contacto/',
                'featured'  => 0,
                'sort_order'=> 1,
            ],
        ],
    ],
];
